services:
  - type: web
    name: s-report
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 180
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: AUTH_USERNAME
        value: NCT1234
      - key: AUTH_PASSWORD
        value: NCT@TP02
